add support for run-bug-run runbugrun #39 WIP
ASSERT-KTH/repairbench-framework pull request #166
Opened 2024-10-30 01:28 UTC by cadddr

https://github.com/ASSERT-KTH/elle-elle-aime/issues/39 WIP

2024-12-03 08:28 UTC, andre15silva commented
Hi @cadddr !

There is currently a failure in the RunBugRun tests.

See https://github.com/ASSERT-KTH/repairbench-framework/actions/runs/12126690735/job/33810455158?pr=166#step:13:337

Seems to be an error in loading the dataframe.

2024-12-03 17:33 UTC, cadddr commented
Since this isn’t file not found, could be a version/deprecation issue with
pandas? What version is being installed, so I can reproduce? Thanks

On Mon, Dec 2, 2024 at 10:28 PM André Silva ***@***.***>
wrote:

> Hi @cadddr <https://github.com/cadddr> !
>
> There is currently a failure in the RunBugRun tests.
>
> See
> https://github.com/ASSERT-KTH/repairbench-framework/actions/runs/12126690735/job/33810455158?pr=166#step:13:337
>
> Seems to be an error in loading the dataframe.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ASSERT-KTH/repairbench-framework/pull/166#issuecomment-2513851701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWMCVO4CSBZWZCTHME2NUT2DVTUBAVCNFSM6AAAAABQ3CF6BWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMJTHA2TCNZQGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-03 17:37 UTC, andre15silva commented
> What version is being installed, so I can reproduce?

When you run `poetry install` it will use the version that is defined in the `poetry.lock` file.

Right now that is `2.2.3`

2024-12-16 22:47 UTC, cadddr commented
I also have pandas==2.2.3 In the log there is a deprecation warning for using path string as argument to read_json. Wrapped into file stream. Hopefully this passes, otherwise, not sure how to debug this.

2024-12-17 08:44 UTC, andre15silva commented
Now the problem seems to be related with a FileNotFound.

2024-12-18 00:16 UTC, cadddr commented
> Now the problem seems to be related with a FileNotFound.

My path: `/workspaces/elle-elle-aime/benchmarks/run_bug_run/python_valid0.jsonl`

Double checked commands in setup.sh download and unpack the file correctly:

`mkdir benchmarks/run_bug_run`
`cd benchmarks/run_bug_run`
`wget https://github.com/giganticode/run_bug_run_data/releases/download/v0.0.1/python_valid0.jsonl.gz`
`wget https://github.com/giganticode/run_bug_run_data/releases/download/v0.0.1/tests_all.jsonl.gz`

`gzip -d python_valid0.jsonl.gz`

Why is the working dir in the log `repairbench-framework/repairbench-framework` different from elle-elle-aime ? Could this be the problem?

2024-12-18 11:02 UTC, andre15silva commented
Trying to fix path, and rebased to latest master. Let's see if we can fix this.

2024-12-18 13:28 UTC, andre15silva commented
Fixed the file not found problem by changing the benchmark directory to a submodule.

We not get another error, during the execution of a RunBugRun bug.

2024-12-27 21:55 UTC, cadddr commented
Thanks for fixing the paths. Bug-related errors do not consistently reproduce since we're taking 3 bugs from an unordered dict.  After fixing the order (and running 20 bugs instead of 3), I'm getting the first failure fail on `p02273_118997`.  The reason is fixed solution isn't passing due to the lack of an exact string match. (I mentioned earlier that inputs/outputs in run bug run are being passed via standard io as strings). Example:

print (result)
0 0
11.111111111111112 0.0
16.666666666666668 9.622504486493764
22.222222222222225 0.0
33.333333333333336 0.0
38.88888888888889 9.622504486493762
33.333333333333336 19.24500897298752
44.44444444444444 19.245008972987524
50.0 28.867513459481287
55.55555555555556 19.245008972987527
66.66666666666667 19.245008972987527
61.111111111111114 9.622504486493764
66.66666666666667 0.0
77.77777777777779 0.0
83.33333333333334 9.622504486493753
88.88888888888889 0.0
100 0

print (test_output)
0.00000000 0.00000000
11.11111111 0.00000000
16.66666667 9.62250449
22.22222222 0.00000000
33.33333333 0.00000000
38.88888889 9.62250449
33.33333333 19.24500897
44.44444444 19.24500897
50.00000000 28.86751346
55.55555556 19.24500897
66.66666667 19.24500897
61.11111111 9.62250449
66.66666667 0.00000000
77.77777778 0.00000000
83.33333333 9.62250449
88.88888889 0.00000000
100.00000000 0.00000000

2024-12-28 16:59 UTC, andre15silva commented
Thanks for noticing the randomness bug! I fixed the issue for all benchmarks and rebased this PR with the latest commits from master.

For the problem of comparing outputs, the straigh-forward solution would be to eval the strings and compare the values.
Are the outputs always floats or can they be of other types?

2025-03-11 00:26 UTC, cadddr commented
@andre15silva PR back from the dead. I imported output post-processing logic from runbugrun, now tests pass. Please check if this is mergeable.

2025-03-11 09:55 UTC, andre15silva commented
/gemini review

2025-03-11 10:08 UTC, andre15silva requested changes

2025-03-11 10:08 UTC, andre15silva commented on elleelleaime/core/utils/python/python.py
> +            fixed_code = f.read()
This currently uses the hardcoded paths from RunBugRun, but the Python utils should not depend on it.

Can you check the implementation by @t-sorger in https://github.com/ASSERT-KTH/repairbench-framework/pull/184? I've already reviewed the abstraction and implementation logic of that part of the PR, and would be nice if we could merge the two

2025-03-11 10:08 UTC, andre15silva commented on elleelleaime/core/benchmarks/runbugrun/runbugrunbug.py
> +        cmd = f"cd {self.benchmark.get_path()}; mkdir {path}/buggy; cp {subfolder}/{self.identifier}.py {path}/buggy"  # FIXME
This is fine since the benchmark is fixed.

Can you remove the FIXME comment?

2025-03-11 10:10 UTC, andre15silva commented
Thanks @cadddr !

I went over the code again and also ran the Gemini review.
Linting is failing, could you run the linter (there is a pre-commit hook for that now)?

Left some comments and waiting for the tests to run.

2025-03-11 18:10 UTC, cadddr commented
> Thanks @cadddr !
> 
> I went over the code again and also ran the Gemini review. Linting is failing, could you run the linter (there is a pre-commit hook for that now)?
> 
> Left some comments and waiting for the tests to run.

@andre15silva sure I can run linking and remove FIXME comments. Tests are failing with run bug run json file being not found. I noticed download commands for that have been removed from setup.sh -- why is that? Should I simply rollback the file to the version that worked?

2025-03-11 18:18 UTC, cadddr commented
@andre15silva Data download commands for runbugrun were removed in this commit: https://github.com/cadddr/elle-elle-aime/commit/b83f85589c5c996ecf194baa919d055b5bbac86f

Initial setting up of benchmarks/run_bug_run was a misunderstanding as the submodule linked to rbugr original ruby repo, whereas the intention for this directory is to simply house the data files. Let me know how best to resolve this.

2025-03-11 18:27 UTC, cadddr commented
@andre15silva also the submodule entry was already taken out here: https://github.com/cadddr/elle-elle-aime/commit/1622d835310f06b0986254c13932b6d20666426d 
Not sure why it was  brought back. Could all that be overwritten by merge from ASSERT-KTH:master ?

2025-03-11 19:03 UTC, cadddr commented on elleelleaime/core/utils/python/python.py
> +            fixed_code = f.read()
@andre15silva there also seems to be some hardcoding and dataset-specific logic in that PR. A simple portable solution I can think of is for checkout to return the path it actually checked out into (since that function is responsible for hardcoding "buggy" in the first place). Not every bug class has to support this, I can simply check if there is a returned value.

2025-03-11 19:49 UTC, andre15silva commented
Could have been problems with the merge, not sure what happened.

We can fix the setup.sh, the version in `main` doesn't have this issue.
As for the submodule or not, if the files are not the same as the repo then we can simply add the in a directory inside `benchmarks`.

WDYT?

2025-03-12 21:12 UTC, cadddr commented
@andre15silva made all changes, let's see those tests pass.

2025-03-13 17:50 UTC, cadddr commented
@andre15silva 
Tests are failing due to file paths issues. File not found here: '/home/runner/work/repairbench-framework/repairbench-framework/benchmarks/run_bug_run/python_valid0.jsonl'

When running set up this file gets downloaded but not to the right directory as the preceding cd command fails:
./setup.sh: line 27: cd: benchmarks/run_bug_run: No such file or directory

This directory exists in the repo e.g., https://github.com/cadddr/elle-elle-aime/blob/master/benchmarks/run_bug_run/buggy_test_results.tgz

For me pwd shows: /workspaces/elle-elle-aime, I recall we had this issue before e.g., https://github.com/ASSERT-KTH/repairbench-framework/pull/166#issuecomment-2549964321 
How did you fix it?

2025-03-14 08:43 UTC, andre15silva requested changes

2025-03-14 08:43 UTC, andre15silva commented on setup.sh
> +
```suggestion
fi
cd ../..;

```

2025-03-14 08:43 UTC, andre15silva commented on setup.sh
> +
This fixes the path problem in `setup.sh`

2025-03-14 17:13 UTC, cadddr commented
@andre15silva look like all tests pass! we're all set to merge?

2025-03-17 17:43 UTC, andre15silva commented
LGTM!

Let's wait for @t-sorger to take a look and give his opinion and then we can merge. He's also been working on integrating another Python benchmark.

2025-03-17 17:43 UTC, andre15silva approved these changes

2025-03-18 22:41 UTC, t-sorger commented
The code generally looks good to me.

I do have some concerns about the Python utilities, as I ran this code previously with slight modifications while developing my own version. It might not be fully compatible with the BugsInPy benchmark, so it’s something to keep in mind when integrating BugsInPy to ensure the utilities don’t break for run-bug-run (and vice versa). That said, it should be fine for now.

2025-03-18 22:58 UTC, cadddr commented
Admittedly, I've put in the bare minimum needed just to make Run bug run work. Agreed they will have to be generalized as we onboard more python datasets, perhaps in the next PR. With this second dataset BugsInPy we should get a better idea of what parts are general vs dataset-specific.

2025-03-19 08:13 UTC, andre15silva commented
Sounds good, merging it.

Good work @cadddr, thanks for the PR :))

2025-03-19 08:13 UTC, merged